package com.wjwcloud.iot.utils.redis;

public interface CacheKeyConstant {
    String INFORMATIONONEPAGE_KEY = "INFORMATIONONEPAGE_KEY";
    String CURRSYSTEMP_KEY = "CURRSYSTEMP_KEY";
    String CURRSTATISTICSCODE_KEY = "CURRSTATISTICSCODE_KEY";
    String SHOPKUAISHANG_KEY = "SHOPKUAISHANG_KEY";
    String CURRMOBSITEBASIC_KEY = "CURRMOBSITEBASIC_KEY";
    String SEO_KEY = "SEO_KEY";
    String BASICSET_KEY = "BASICSET_KEY";
    String TOPSHARE_KEY = "TOPSHARE_KEY";
    String HELPCATELIST_KEY = "HELPCATELIST_KEY";
    String ALLISFOOT_KEY = "ALLISFOOT_KEY";
    String HOTSEARCH_KEY = "HOTSEARCH_KEY";
    String CHANNELADVER_KEY = "CHANNELADVER_KEY";
    String TEMPTOKEN_KEY = "TEMPTOKEN_KEY";
}
