server:
   port: 8080

spring:
  mvc:
    static-path-pattern: /**

  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
#  redis:
#    host: localhost
#    # 连接超时时间（记得添加单位，Duration）
#    timeout: 10000ms
#    # Redis默认情况下有16个分片，这里配置具体使用的分片
#    # database: 0
#    lettuce:
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制） 默认 8
#        max-active: 8
#        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
#        max-wait: -1ms
#        # 连接池中的最大空闲连接 默认 8
#        max-idle: 8
#        # 连接池中的最小空闲连接 默认 0
#        min-idle: 0
#    password: admin
#  cache:
#    # 一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配
#    type: redis
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/iot_v1?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
# mybatis 配置
mybatis:
    type-aliases-package: package com.wjwcloud.iot.*.entity
    mapper-locations: classpath:./*/mapper/*.xml
    #配置驼峰下划线
    configuration:
      map-underscore-to-camel-case: true

logging:
  level:
    com.wjwcloud: debug
